### ISSUE TITLE
알림기능 추가

### ISSUE THREAD

**Issue by grjsm99** [leegeunhyeok/BitMiner#7]
**기능 요청**
코인시세변동때마다 알림이 뜨면 좋을거같아요.

+ 
![image](https://user-images.githubusercontent.com/44054161/49632496-473c1580-fa39-11e8-97e4-8826ac8aa8da.png)
새집에서 나오지않는 이미지가 있어요.

**Comment by leegeunhyeok** [comment]
모니터 이미지가 나오지 않는 문제는 곧 해결될 예정입니다.
시세 변동 시 알림이 오는 기능은 추가 아이템 구매를 통해 사용하실 수 있도록 업데이트 할 예정입니다.

감사합니다.

**Comment by leegeunhyeok** [comment]
@grjsm99 모니터 이미지 표기 오류는 [aa52f0](https://github.com/leegeunhyeok/BitMiner/commit/aa52f03ddba80ec808367df2313aab60ac93f3f2)를 통해 해결되었습니다.
